### ISSUE TITLE
should return BadCertificateRevocationUnknown when corresponding CRL file is missing.

### ISSUE THREAD

**Issue by erossignon** [node-opcua/node-opcua-crypto#23]

**Comment by jforge** [comment]
@erossignon  Is this always correct?

Actually,  CRLs (Certificate Revocation Lists) are optional for private/internal certificates, but they are strictly required for publicly trusted certificates in the Web PKI.

Therefore, rejecting private/internal certificates for a missing CRL is actually wrong, or is there some configuration to control the behaviour?

**Comment by erossignon** [comment]
BadCertificateRevocationUnknown is used when the server/client leaf certificate is not self-signed but issued by a CA Authority. In this case, the PKI must trust the CA Certificate (root and intermediate if any). 
The CA Certificates contain information about how to access the revocation list.
This could be using a https endpoint. Alternatively, the PKI may use a cached CRL or provide valid CRL installed. . It has been 3 years ago, when this issue was raised that was the only solution supported by the pki engine. 

node-opcua-pki anda node-opcua-crypto chave now a more robust capabilties to check the revocation status of a chained certificate.

**Comment by jforge** [comment]
OK, understand, thank you for the fast answer.

My point is a (typical) private/internal PKI, which indeed has a (self-signed/created) root CA, maybe intermediate CAs and a couple of server/client certs (what private PKIs typically might provide); well-designed private enterprise PKI sytem might provide proper CRLs or OCSP servers or nothing of that, because CRLs and OCSP are technically optional by the standard. But OK, from a compliance point of view they might be practically mandatory.

A node-opcua should IMHO offer an option to accept certs without CRL and OCSP. And also tolerate, if PKIs work only with the more modern OCSP only and no CRLs at all. I'm aware of the recommendations to provide both OCSP and CRL to make sure there is some fallback, but I'm confused, that OCPUA seems to make CRLs mandatory?

Maybe I miss a configuration option for this, in the node-opcua-pki module?
